"""empty message

Revision ID: 23e77b8eb11e
Revises: 6dce4d36cc95
Create Date: 2021-05-09 19:30:36.218652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e77b8eb11e'
down_revision = '6dce4d36cc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', sa.Integer(), nullable=False))
    op.drop_constraint('comment_user_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['author'], ['uid'], ondelete='CASCADE')
    op.drop_column('comment', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_user_fkey', 'comment', 'user', ['user'], ['uid'], ondelete='CASCADE')
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###
