"""empty message

Revision ID: 64719dba1447
Revises: f1c021194c54
Create Date: 2021-05-06 17:20:00.689071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64719dba1447'
down_revision = 'f1c021194c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('title', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'title')
    # ### end Alembic commands ###
