"""empty message

Revision ID: 6dce4d36cc95
Revises: 64719dba1447
Create Date: 2021-05-06 19:23:37.302393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dce4d36cc95'
down_revision = '64719dba1447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_post_author_fkey', 'blog_post', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post', 'user', ['author'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('comment_user_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_blog_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'blog_post', ['blog'], ['blogid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_blog_fkey', 'comment', 'blog_post', ['blog'], ['blogid'])
    op.create_foreign_key('comment_user_fkey', 'comment', 'user', ['user'], ['uid'])
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.create_foreign_key('blog_post_author_fkey', 'blog_post', 'user', ['author'], ['uid'])
    # ### end Alembic commands ###
